[versions]
agp = "9.2.1"
desugar_jdk_libs = "2.1.5"
kotlin = "2.4.10"
coreKtx = "1.19.0"
junit = "4.13.2"
androidlifecycle = "2.11.0"
activityCompose = "1.13.0"
composeBom = "2026.06.01"
koin = "4.2.2"
navigation3 = "1.1.4"
coroutines = "1.11.0"
mockk = "1.14.11"
kotest = "6.2.2"
turbine = "1.2.1"
detekt = "1.23.8"
room = "2.8.4"
datastore = "1.2.1"
jetbrainsKotlinJvm = "2.4.10"
reorderable = "3.1.0"
ktor = "3.5.1"
ksp = "2.3.6"
leakcanary = "2.14"
firebase-bom = "34.16.0"
google-services = "4.5.0"
firebase-crashlytics-gradle = "3.0.7"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidlifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidlifecycle" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

#Test Core
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# Coroutines Test
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
# MockK
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
# Kotest Assertions
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core-jvm", version.ref = "kotest" }
# Turbine (Flow Testing)
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

#Navigation3
androidx-navigation3-runtime = {module = "androidx.navigation3:navigation3-runtime",version.ref = "navigation3"}
androidx-navigation3-ui = {module = "androidx.navigation3:navigation3-ui",version.ref = "navigation3"}
androidx-navigation3-viewmodel = {module= "androidx.lifecycle:lifecycle-viewmodel-navigation3",version.ref = "androidlifecycle"}

# Koin
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }

#Room
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

#Datastore
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

#Ktor
ktor-client-core = {module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktor-client-android = {module = "io.ktor:ktor-client-android", version.ref = "ktor"}

#Reorderable
reorderable = { group = "sh.calvin.reorderable", name = "reorderable-android", version.ref = "reorderable" }

#LeakCanary
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

#Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = {id = "io.gitlab.arturbosch.detekt", version.ref = "detekt"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = {id = "androidx.room", version.ref = "room"}
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
